version: '3.9'

services:
  file-storage-db:
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_ARGS: --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - '6379:6379'
    volumes: 
      - file-storage-db:/data
volumes:
  file-storage-db:
    driver: local