version: '3.9'

services:
  file-storage-db:
    image: redis:7.0.4
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - file-storage-db:/data
volumes:
  file-storage-db:
    driver: local