# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: File Storage CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache-dependency-path: storage-ui/package-lock.json
          cache: 'npm'
      - name: Install dependencies && check types
        working-directory: storage-ui
        run: |
          npm ci
          npm run type-check
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache-dependency-path: storage-ui/package-lock.json
          cache: 'npm'
      - name: Install dependencies && run test
        working-directory: storage-ui
        run: |
          npm ci
          npm run test:unit
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    needs: [type-check, unit-test]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache-dependency-path: storage-ui/package-lock.json
          cache: 'npm'
      - name: Install dependencies && run build
        working-directory: storage-ui
        run: |
          npm ci
          npm run build
